name: CI/CD Pipeline

on:
  push:
    paths:
      - "serverless-start/**"
      - "serverless-extra/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # service: [firestore, get-firestore, ml-endpoint-middleware]
        service: [serverless-start, serverless-extra]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          cd ${{ matrix.service }}
          npm install

      # - name: Run tests here
      #   run: |
      #    npm run test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [serverless-start, serverless-extra]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Serverless
        run: |
          cd ${{ matrix.service }}
          npx serverless deploy

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
