name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  determine_changes:
    runs-on: ubuntu-latest
    outputs:
      step1_changed: ${{ steps.step1.outputs.changed }}
      step2_changed: ${{ steps.step2.outputs.changed }}
      # step3_changed: ${{ steps.step3.outputs.changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine changes
        id: step1
        run: |
          SERVICE1_CHANGED=$(if git diff --quiet --exit-code ${{ github.sha }}^1 ${{ github.sha }} -- 'serverless-start/'; then
            echo false
          else
            echo true
          fi)
          echo "SERVICE1_CHANGED=${SERVICE1_CHANGED}"
          echo "SERVICE1_CHANGED=${SERVICE1_CHANGED}" >> $GITHUB_STATE

      - name: Determine changes
        id: step2
        run: |
          SERVICE2_CHANGED=$(if git diff --quiet --exit-code ${{ github.sha }}^1 ${{ github.sha }} -- 'serverless-extra/'; then
            echo false
          else
            echo true
          fi)
          echo "SERVICE1_CHANGED=${SERVICE2_CHANGED}"
          echo "SERVICE1_CHANGED=${SERVICE2_CHANGED}" >> $GITHUB_STATE

      # - name: Determine changes
      #   id: step3
      #   run: echo "::set-output name=changed::$(if git diff --name-only ${{ github.sha }}..origin/main | grep '^ml-endpoint-middleware-services/'; then echo true; else echo false; fi)"

  build:
    needs: determine_changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # service: [firestore, get-firestore, ml-endpoint-middleware]
        service: [serverless-start, serverless-extra]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          cd ${{ matrix.service }}
          npm install

      - name: Check for changes
        run: echo "CHANGED=$(cat $GITHUB_STATE | grep '^SERVICE1_CHANGED=' | cut -d'=' -f2)" >> $GITHUB_ENV
      # - name: Run tests
      #   run: |
      #    if [ "${{ env.CHANGED }}" != "true" ]; then
      # echo "No changes detected. Skipping build."
      # else
      # echo "Changes detected. Running build."
      # Your build steps here
      # fi

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # service: [firestore, get-firestore, ml-endpoint-middleware]
        service: [serverless-start, serverless-extra]
      fail-fast: ${{ needs.build.outputs.step1_changed != 'true' && needs.build.outputs.step2_changed != 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes
        run: echo "CHANGED=$(cat $GITHUB_STATE | grep '^SERVICE1_CHANGED=' | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Deploy to Serverless
        run: |
          if [ "${{ env.CHANGED }}" != "true" ]; then
            echo "No changes detected. Skipping deploy."
          else
            echo "Changes detected. Running deploy."
            cd ${{ matrix.service }}
           npx serverless deploy
           fi

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
