name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  determine_changes:
    runs-on: ubuntu-latest
    outputs:
      step1_changed: ${{ steps.step1.outputs.changed }}
      step2_changed: ${{ steps.step2.outputs.changed }}
      # step3_changed: ${{ steps.step3.outputs.changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine changes
        id: step1
        run: echo "::set-output name=changed::$(if git diff --name-only ${{ github.sha }}..origin/main | grep '^serverless-start/'; then echo true; else echo false; fi)"

      - name: Determine changes
        id: step2
        run: echo "::set-output name=changed::$(if git diff --name-only ${{ github.sha }}..origin/main | grep '^serverless-extra/'; then echo true; else echo false; fi)"

      # - name: Determine changes
      #   id: step3
      #   run: echo "::set-output name=changed::$(if git diff --name-only ${{ github.sha }}..origin/main | grep '^ml-endpoint-middleware-services/'; then echo true; else echo false; fi)"

  build:
    needs: determine_changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # service: [firestore, get-firestore, ml-endpoint-middleware]
        service: [serverless-start, serverless-extra]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          cd ${{ matrix.service }}
          npm install

      - name: Check for changes
        run: echo "::set-output name=changed::$(if git diff --name-only ${{ github.sha }}..origin/main | grep '^serverless-start/'; then echo true; else echo false; fi)"

      # - name: Run tests
      #   run: |
      #     if [ "${{ needs.build.outputs.changed }}" != "true" ]; then
      #       echo "No changes detected. Skipping build."
      #     else
      #       echo "Changes detected. Running build."
      #       # Your build steps here
      #     fi

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # service: [firestore, get-firestore, ml-endpoint-middleware]
        service: [serverless-start, serverless-extra]
      fail-fast: ${{ needs.build.outputs.step1_changed != 'true' && needs.build.outputs.step2_changed != 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes
        run: echo "::set-output name=changed::$(if git diff --name-only ${{ github.sha }}..origin/main | grep '^serverless-start/'; then echo true; else echo false; fi)"

      - name: Deploy to Serverless
        run: |
          if [ "${{ needs.deploy.outputs.changed }}" != "true" ]; then
             echo "No changes detected. Skipping deploy."
           else
             echo "Changes detected. Running deploy."
             cd ${{ matrix.service }}
           npx serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
